name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Start all the environment
        run: build.sh start

      - name: Configure all the environment
        run: build.sh configure

      - name: Run the tests
        run: build.sh test
